### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by KunkkaCoco** [limboy/chat#4]
[root@chwch chat]# python bootstrap.py 
Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
Traceback (most recent call last):
  File "bootstrap.py", line 258, in <module>
    ws.require(requirement)
  File "/tmp/tmpu13QMC/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
  File "/tmp/tmpu13QMC/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 569, in resolve
pkg_resources.VersionConflict: (setuptools 0.6c11 (/tmp/tmpu13QMC/setuptools-0.6c11-py2.7.egg), Requirement.parse('setuptools>=3.3'))

why? please help me!

**Comment by tr0yspradling** [comment]
Possibly version mismatch?
